language: php

php:
  - '7.1'
  

    
addons:
  sonarcloud:
    organization: kimfml
    token:
      secure: ••••••••••••••••
      
dist: xenial 
git:
  depth: false 

env:
  - DB=mysql

install: composer update --no-interaction --no-suggest --no-progress

before_script: 
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS yiitest;'; fi"
  - composer require atoum/atoum
  
script:
  #- vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage-report.clover --log-junit=test-report.xml
  - sonar-scanner
  
        




