dist: xenial

addons:
  sonarcloud:
    organization: kimfml 
    token:
      secure: •••••••••••••••• 

language: php

php:
  - '7.0'

env:
  - SYMFONY_VERSION="2.0.*" DB=mysql
  - SYMFONY_VERSION="dev-master" DB=mysql


script:
  - sonar-scanner


sonar.python.coverage.reportPaths=/home/travis/build/Wiyiiong/Red-DiscordBot/cov.xml
sonar.python.xunit.reportPath=/home/travis/build/Wiyiiong/Red-DiscordBot/pytest-report.xml

