language: php
git:
  depth: false
php:
  - '7.0'
  
addons:
  sonarcloud:
    organization: kimfml
    token:
      secure: •••••••••••••••• 

env:
  - SYMFONY_VERSION="2.0.*" DB=mysql
  - SYMFONY_VERSION="dev-master" DB=mysql

before_script: composer require atoum/atoum
script:
  - vendor/bin/atoum
  - vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage-report.clover --log-junit=test-report.xml
  - sonar-scanner
  

        




