dist: xenial

addons:
  sonarcloud:
    organization: kimfml 
    token:
      secure: •••••••••••••••• 
script:
  - sonar-scanner


language: php

notifications:
  email: false

php:
-7.0

script:
  - sonar-scanner


