language: php

notifications:
  email: false

php:
-7.0

install:
- pip install --upgrade pip tox
- pip install pytest-mock
- pip install pytest-asyncio
- pip install -e .
- pip install ."[tests]"
- pip install coverage
- pip install setuptools
- pip install pytest-cov



