language: php

php:
  - '7.0'
  
cache:
  directories:
    - $HOME/.composer/cache
    
addons:
  sonarcloud:
    organization: kimfml
    token:
      secure: ••••••••••••••••
 
git:
  depth: false 

env:
  - SYMFONY_VERSION="2.0.*" DB=mysql
  - SYMFONY_VERSION="dev-master" DB=mysql

install: composer update --no-interaction --no-suggest --no-progress

before_script: composer require atoum/atoum
script:
  - vendor/bin/phpunit -c phpunit2.xml.dist --coverage-clover=coverage-report.clover --log-junit=test-report.xml
  - sonar-scanner
  
        




