language: php

php:
  - '5.4'
  - '5.6'
  - '7.0'

env:
  - SYMFONY_VERSION="2.0.*" DB=mysql
  - SYMFONY_VERSION="dev-master" DB=mysql

before_script: composer require atoum/atoum
script: vendor/bin/atoum

install: php vendor/vendors.php