language: php

php:
  - '7.1'
  

    
addons:
  sonarcloud:
    organization: kimfml
    token:
      secure: ••••••••••••••••
      
dist: xenial 
git:
  depth: false 

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

install: composer update --no-interaction --no-suggest --no-progress

before_script: composer require atoum/atoum
script:
  #- vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage-report.clover --log-junit=test-report.xml
  - tox
  - sonar-scanner
  
        




